/** @format */

let shopItemsData = [
  {
    id: 'jfhgbvnscs',
    name: 'Casual Shirt',
    price: 45,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing.',
    img: 'Assets/img-1.jpeg',
    tag: ['tshirt', 'shirt'],
  },
  {
    id: 'ioytrhndcv',
    name: 'Office Shirt',
    price: 100,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing.',
    img: 'Assets/img-2.jpeg',
    tag: ['tshirt', 'shirt'],
  },
  {
    id: 'wuefbncxbsn',
    name: 'T Shirt',
    price: 25,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing.',
    img: 'Assets/img-3.jpeg',
    tag: ['tshirt'],
  },
  {
    id: 'thyfhcbcv',
    name: 'Mens Suit',
    price: 300,
    desc: 'This piece of fabrique will make you look elegant on all occasions because of its unique design.Lorem ipsum dolor sit amet consectetur adipisicing',
    img: 'Assets/img-4.jpg',
    tag: ['suit', 'mens suit'],
  },
  {
    id: 'thiecbawdjksadjk',
    name: 'Mens Tie',
    price: 25,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing.',
    img: 'Assets/img-5.jpg',
    tag: ['tie', 'ems tie'],
  },
  {
    id: 'iuertrywebncdjksadjk',
    name: 'Casual shoes',
    price: 200,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing.',
    img: 'Assets/img-6.jpg',
    tag: ['shoes', 'casual shoes'],
  },
  {
    id: 'thierytbvcbvzdhadjk',
    name: 'Black suit',
    price: 450,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing.',
    img: 'Assets/img-7.png',
    tag: ['suit', 'black suit'],
  },
  {
    id: 'trfoiwfcnbcawdjksadjk',
    name: 'Polo shirt',
    price: 45,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing.',
    img: 'Assets/img-8.jpg',
    tag: ['polo', 'shirt'],
  },
  {
    id: 'cbvxbcvsceldk',
    name: 'Denim shirt',
    price: 85,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing.',
    img: 'Assets/img-9.jpg',
    tag: ['denim', 'shirt'],
  },
  {
    id: 'oiopijmjkhuihb',
    name: 'Denim pants',
    price: 120,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing.',
    img: 'Assets/img-10.jpg',
    tag: ['pants'],
  },
  {
    id: 'oiopijmjkhuohb',
    name: 'Red T Shirt',
    price: 120,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing.',
    img: 'Assets/red-t-shirt.jpg',
    tag: ['tshirt', 'shirt'],
  },
  {
    id: 'oiopijewyiohbjhib',
    name: 'Basic cap',
    price: 35,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing.',
    img: 'Assets/img-11.jpg',
    tag: ['cap'],
  },
  {
    id: 'rtytytuyuytyytbvncv',
    name: 'leather boots',
    price: 350,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing.',
    img: 'Assets/img-12.jpg',
    tag: ['leather boots', 'shoes', 'boots'],
  },
  {
    id: 'rtytytuyuytyyfbvncv',
    name: 'Mens brown tie',
    price: 350,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing.',
    img: 'Assets/men-brown-tie.jpg',
    tag: ['tie', 'brown tie'],
  },
  {
    id: 'rtytytuyuytyytbvncv',
    name: 'Bow Tie',
    price: 350,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing.',
    img: 'Assets/men-bow-tie.jpg',
    tag: ['tie', 'men bow tie'],
  },
];
